### ISSUE TITLE
SDK_CRAWLER_STATISTICS_0 values are cumulative - not being overwritten

### ISSUE THREAD

**Issue by MSIH** [apify/apify-storage-local-js#33]
When running locally on linux, If I run the same job (npm run start), the file SDK_CRAWLER_STATISTICS_0 does not get overwritten, instead, the data values are added/cumulative. Specifically, itemCount. Run first time and crawl 10 items, itemCount=10. Run second time and crawl 10 items, itemCount=20.

        const getStats = await Apify.getValue('SDK_CRAWLER_STATISTICS_0');
        console.dir(getStats);

See https://github.com/apify/apify-js/blob/master/src/crawlers/statistics.js

**Comment by mnmkng** [comment]
Yes, that is expected. If you want separate stats for each run you should clear the storages either by running `apify run -p`, manually, or programmatically by deleting this specific value from the key-value store.

**Comment by MSIH** [comment]
I understand that is how the sdk works but I would not say most people would consider that "expected" behavior when running locally. On the Apify platform, each run has own storage folder, but not the case when run locally. 

I would of thought that the last number would increment each time the crawl was run.

**Comment by mnmkng** [comment]
Yeah, it's not very intuitive, but if we overwrite the stats automatically, then other users, who do incremental crawls, would not be able to track total crawling stats. We chose to support both repeated and incremental crawls, at the cost of a less intuitive interface for the repeated crawls.
